# These are supported funding model platforms

patreon: akopachov
ko_fi: akopachov
custom: ["https://www.buymeacoffee.com/mijumoho", "https://donorbox.org/flipper-authenticator", "https://buycoffee.to/akopachov"]
