name: VirusTotal scan for release

on:
  release:
    types: [released]

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          request_rate: 4
          files: |
            .exe$
            .dmg$
            .AppImage$